- name: Configure DevOps VM
  hosts: devops
  become: true

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - docker.io
          - python3-pip
          - git
        state: present

    - name: Add a user to the docker group
      ansible.builtin.user:
        name: devops
        groups: docker
        append: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create a Docker network named monitoring
      docker_network:
        name: monitoring
        state: present

    - name: Run Grafana in Docker
      docker_container:
        name: grafana
        image: grafana/grafana-oss:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        networks:
          - name: monitoring

    - name: Run Prometheus in Docker
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - /opt/prometheus:/etc/prometheus
        networks:
          - name: monitoring

    - name: Copy prometheus.yml
      copy:
        src: files/prometheus.yml
        dest: /opt/prometheus/prometheus.yml

    - name: Add Prometheus as a data source in Grafana
      community.grafana.grafana_datasource:
        name: Prometheus
        ds_type: prometheus
        ds_url: "http://{{ host_ip }}:9090"
        access: proxy
        is_default: true
        state: present
        grafana_url: "http://{{ host_ip }}:3000"
        grafana_user: admin
        grafana_password: admin

    - name: Run Node Exporter in Docker
      docker_container:
        name: node_exporter
        image: prom/node-exporter
        state: started
        restart_policy: always
        ports:
          - "9100:9100"
        networks:
          - name: monitoring

    - name: Copy the dashboard file to the remote VM
      copy:
        src: files/sample-dashboard.json
        dest: /tmp/sample-dashboard.json

    - name: Add Node Exporter Full Dashboard in Grafana
      community.grafana.grafana_dashboard:
        grafana_url: "http://{{ host_ip }}:3000"
        grafana_user: admin
        grafana_password: admin
        path: /tmp/sample-dashboard.json
        state: present
        overwrite: true
